-- Create chicken_breeds table
CREATE TABLE public.chicken_breeds (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  category text,
  description text,
  excerpt text,
  origin text,
  hen_weight_kg text,
  rooster_weight_kg text,
  eggs_per_year text,
  egg_size text,
  egg_color text,
  laying_notes text,
  temperament text,
  broodiness text,
  climate_adaptability text,
  appearance text,
  availability text,
  introduced_year int,
  availability_notes text,
  image_url text,
  traits text[],
  created_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.chicken_breeds ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access (breeds are public info)
CREATE POLICY "Anyone can view chicken breeds"
  ON public.chicken_breeds
  FOR SELECT
  USING (true);

-- Insert seed data based on existing breeds
INSERT INTO public.chicken_breeds (name, slug, category, description, excerpt, origin, hen_weight_kg, rooster_weight_kg, eggs_per_year, egg_size, egg_color, laying_notes, temperament, broodiness, climate_adaptability, appearance, availability, image_url, traits) VALUES
(
  'Orpingtons',
  'orpingtons',
  'dual-purpose',
  'Orpingtons are a British breed of chicken developed in the late 19th century. They are known for their large size, gentle nature, and exceptional egg-laying capabilities. Our Orpingtons are bred for both beauty and functionality, making them perfect for families and backyard enthusiasts alike. They come in various colors including buff, black, blue, and white.',
  'Known for their gentle nature and exceptional egg-laying capabilities, our Orpingtons are bred for both beauty and functionality.',
  'Kent, England - Developed by William Cook in 1886',
  '3.2–3.6',
  '4.1–4.5',
  '200–280',
  'Large',
  'Brown',
  'Consistent layers throughout the year, may slow during winter months',
  'Gentle, Docile, Friendly',
  'High - excellent mothers',
  'Cold hardy, adapts well to confinement',
  'Large, heavy body with fluffy feathers. Low stance with curved back.',
  'Bulawayo, Zimbabwe - Atomc Chickens',
  'https://cdn.pixabay.com/photo/2015/11/20/12/54/bird-1053045_1280.jpg',
  ARRAY['Gentle', 'Good Layers', 'Family Friendly']
),
(
  'Brahmas',
  'brahmas',
  'dual-purpose',
  'Brahmas are majestic giants among chickens, known for their impressive size and calm demeanor. Originally developed from birds imported from China, they became one of the most popular meat birds in the United States from the 1850s until about 1930. Today, they are prized as show birds and backyard pets for their gentle nature and striking appearance.',
  'Majestic and imposing, Columbian Brahmas are gentle giants that make excellent winter layers and stunning show birds.',
  'United States - Developed from Chinese imports in the 1840s',
  '4.1–4.5',
  '5.4–5.9',
  '150–200',
  'Medium to Large',
  'Brown',
  'Excellent winter layers, continue laying when other breeds slow down',
  'Docile, Calm, Gentle Giants',
  'Moderate',
  'Excellent cold tolerance, feathered feet provide insulation',
  'Very large birds with feathered legs and feet, pea comb, and upright posture.',
  'Bulawayo, Zimbabwe - Atomc Chickens',
  'https://cdn.pixabay.com/photo/2019/03/10/17/38/hen-brahma-4046755_1280.jpg',
  ARRAY['Winter Hardy', 'Show Quality', 'Docile']
),
(
  'Frizzle Orpingtons',
  'frizzle-orpingtons',
  'ornamental',
  'Frizzle Orpingtons combine the beloved temperament of standard Orpingtons with the extraordinary appearance of frizzled feathers. Each feather curls outward and upward, creating a unique fluffy appearance that makes these birds stand out in any flock. Despite their unusual looks, they retain all the wonderful qualities of their Orpington heritage.',
  'These unique birds feature distinctively curled feathers, combining the beloved Orpington temperament with extraordinary appearance.',
  'Developed from Orpington crosses with Frizzle genetics',
  '2.7–3.2',
  '3.6–4.1',
  '160–200',
  'Medium to Large',
  'Brown to Cream',
  'Good layers but slightly less productive than standard Orpingtons',
  'Friendly, Curious, Docile',
  'Moderate to High',
  'Needs protection from extreme weather due to feather structure',
  'Distinctive curled feathers pointing outward, giving a fluffy appearance.',
  'Bulawayo, Zimbabwe - Atomc Chickens',
  '/img/IMG_0304.jpg',
  ARRAY['Unique Appearance', 'Friendly', 'Hardy']
),
(
  'Wyandottes',
  'wyandottes',
  'dual-purpose',
  'Wyandottes are a stunning American breed developed in New York in the 1870s. They are known for their beautiful laced feathering patterns and rose comb. Wyandottes are excellent dual-purpose birds that are cold hardy and make wonderful additions to any backyard flock. They come in many color varieties including silver laced, golden laced, and blue.',
  'Beautiful laced feathering combined with a friendly disposition makes these birds perfect for both show and practical purposes.',
  'New York, United States - Developed in the 1870s',
  '2.7–3.6',
  '3.6–4.3',
  '200–240',
  'Large',
  'Brown to Cream',
  'Reliable layers with good winter production',
  'Calm, Friendly, Good with children',
  'Moderate - can be good mothers',
  'Very cold hardy due to rose comb, heat tolerant as well',
  'Rose comb, rounded body, beautiful laced feather patterns.',
  'Bulawayo, Zimbabwe - Atomc Chickens',
  'https://storageatlasengagepdcus.blob.core.windows.net/atlas/all-media/tfcsouthstatehendecoop/blogs/2023/october-december/chicken.jpg?ext=.jpg',
  ARRAY['Beautiful Plumage', 'Good Mothers', 'Winter Hardy']
),
(
  'Rhode Island Reds',
  'rhode-island-reds',
  'dual-purpose',
  'Rhode Island Reds are one of the most successful dual-purpose breeds ever developed. Originating in Rhode Island and Massachusetts in the late 1800s, they are renowned for their hardiness, adaptability, and exceptional egg production. These birds are perfect for beginners and experienced chicken keepers alike.',
  'Hardy and resilient, Rhode Island Reds are known for their prolific egg-laying and adaptability to various climates.',
  'Rhode Island & Massachusetts, USA - Late 1800s',
  '2.9–3.4',
  '3.9–4.3',
  '250–300',
  'Large',
  'Brown',
  'Excellent layers, often continue through winter',
  'Hardy, Active, Good foragers',
  'Low',
  'Extremely adaptable to hot and cold climates',
  'Deep mahogany red feathers, yellow legs, single or rose comb.',
  'Bulawayo, Zimbabwe - Atomc Chickens',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPdO039C1LwDok-EzjAKIbt8rP4JE3jtFboZWG3wbsdxi-GUarXVC2B1wJAPm-DKuHoFo&usqp=CAU',
  ARRAY['Dual Purpose', 'Easy Care', 'Good Foragers']
),
(
  'Australorps',
  'australorps',
  'dual-purpose',
  'Australorps hold the world record for egg laying - a hen laid 364 eggs in 365 days! Developed in Australia from Black Orpingtons, they combine excellent egg production with a calm, friendly temperament. Their glossy black feathers have a beautiful green sheen in sunlight, making them both practical and attractive.',
  'Renowned for their prolific egg production and friendly nature, Black Australorps are a favorite among backyard chicken keepers.',
  'Australia - Developed from Black Orpingtons in early 1900s',
  '2.7–3.2',
  '3.6–4.5',
  '250–300',
  'Large',
  'Light Brown',
  'World record holders for egg laying, consistent producers',
  'Calm, Friendly, Easy to handle',
  'Moderate',
  'Good heat and cold tolerance',
  'Glossy black feathers with green sheen, red comb and wattles.',
  'Bulawayo, Zimbabwe - Atomc Chickens',
  'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwsAvfyxiy5IsYHXMR25bl1IV384AOLWPZXA&s',
  ARRAY['Prolific Layers', 'Friendly', 'Adaptable']
);